import type { GamePlan } from "@workspace/api-client-react";

export function gamePlanToMarkdown(plan: GamePlan, idea?: string): string {
  const { designDoc, taskList, technicalChallenges, weeklyPlan } = plan;

  const lines: string[] = [];

  lines.push(`# ${designDoc.title}`);
  if (idea) lines.push(`\n> ${idea}`);
  lines.push("");

  // --- Design Doc ---
  lines.push("## 企划书 / Design Doc");
  lines.push("");
  lines.push(`**Genre:** ${designDoc.genre}`);
  lines.push(`**Platforms:** ${designDoc.platforms.join(", ")}`);
  lines.push(`**Target Audience:** ${designDoc.targetAudience}`);
  lines.push("");
  lines.push("### Concept");
  lines.push(designDoc.concept);
  lines.push("");
  lines.push("### Core Loop");
  lines.push(designDoc.coreLoop);
  lines.push("");

  if (designDoc.features && designDoc.features.length > 0) {
    lines.push("### Key Features");
    for (const f of designDoc.features) {
      lines.push(`- ${f}`);
    }
    lines.push("");
  }

  // --- Task List ---
  lines.push("## 制作任务清单 / Task List");
  lines.push("");

  const categories = [...new Set(taskList.map((t) => t.category))];
  for (const cat of categories) {
    lines.push(`### ${cat.charAt(0).toUpperCase() + cat.slice(1)}`);
    lines.push("");
    const tasks = taskList.filter((t) => t.category === cat);
    for (const task of tasks) {
      lines.push(
        `- **[${task.priority.toUpperCase()}]** ${task.title} *(${task.estimatedHours}h)*`
      );
      if (task.description) {
        lines.push(`  ${task.description}`);
      }
    }
    lines.push("");
  }

  const totalHours = taskList.reduce((sum, t) => sum + t.estimatedHours, 0);
  lines.push(`**Total estimated hours:** ${totalHours}h`);
  lines.push("");

  // --- Technical Challenges ---
  lines.push("## 技术难点 / Technical Challenges");
  lines.push("");
  for (const ch of technicalChallenges) {
    lines.push(`### ${ch.title} \`[${ch.difficulty.toUpperCase()}]\``);
    lines.push(`**Problem:** ${ch.description}`);
    lines.push(`**Solution:** ${ch.solution}`);
    lines.push("");
  }

  // --- Weekly Plan ---
  lines.push("## 一周开发计划 / Weekly Dev Plan");
  lines.push("");
  for (const day of weeklyPlan) {
    lines.push(`### Day ${day.day} — ${day.label}`);
    lines.push(`**Milestone:** ${day.milestone}`);
    lines.push("");
    for (const task of day.tasks) {
      lines.push(`- [ ] ${task}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by 游戏企划生成器*");

  return lines.join("\n");
}

export function downloadMarkdown(plan: GamePlan, idea?: string): void {
  const md = gamePlanToMarkdown(plan, idea);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const slug = (plan.designDoc.title || "game-plan")
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, "-")
    .slice(0, 40);
  a.download = `${slug}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export async function downloadPNG(elementId: string, filename = "game-plan.png"): Promise<void> {
  const { toPng } = await import("html-to-image");
  const el = document.getElementById(elementId);
  if (!el) throw new Error(`Element #${elementId} not found`);

  const dataUrl = await toPng(el, {
    backgroundColor: "#faf9f8",
    pixelRatio: 2,
    skipFonts: false,
    filter: (node) => {
      // Skip fixed/sticky positioned overlays that bleed into the capture
      if (node instanceof HTMLElement) {
        const pos = getComputedStyle(node).position;
        if ((pos === "fixed" || pos === "sticky") && node.id !== elementId) {
          return false;
        }
      }
      return true;
    },
  });

  const a = document.createElement("a");
  a.href = dataUrl;
  a.download = filename;
  a.click();
}
